### ISSUE TITLE
Error: EACCES: permission denied

### ISSUE THREAD

**Issue by ZengTianShengZ** [hawx1993/hbuild#1]
when i start developing
```
 npm run dev
```
The console prints an error
```


[10:46:27] Local version 3.9.1
zengtianshengdeMacBook-Pro-3:hbuild-poj ZengTianSheng$ npm run dev


> hbuild-poj@1.0.2 dev /Users/bong/WebstromProjects2/hbuild-poj
> gulp dev --dev

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/Users/bong/WebstromProjects2/hbuild-poj/node_modules/.1.0.0@array-slice/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.Module._extensions..js (module.js:431:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/bong/WebstromProjects2/hbuild-poj/node_modules/.1.1.0@object.defaults/immutable.js:3:13)
    at Module._compile (module.js:425:26)

```

my versions
```
node v5.0.0
npm v3.3.6
gulp v3.9.1
```

**Comment by hawx1993** [comment]
try sudo npm run dev
